# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awesome', '0007_auto_20160430_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_img',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='awesome.Tag'),
        ),
    ]
