# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awesome', '0008_auto_20160510_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='steam_appid',
            field=models.IntegerField(null=True),
        ),
    ]
